services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production
      - PORT=6000
    networks:
      - app-network

  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
